# Ansible Playbook for my web application jarombek.com AMI
# Author: Andrew Jarombek
# Date: 3/22/2019

- name: App
  hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: Clone Git Repository
      become: yes
      git:
        repo: https://github.com/AJarombek/jarombek-com.git
        version: master
        dest: ~/jarombek-com

    - name: Install Application Dependencies
      become: yes
      yarn:
        path: ~/jarombek-com/

    - name: Install Application Dependencies
      become: yes
      command: "{{item}}"
      with_items:
        - cd ~/jarombek-com/
        - yarn server:build
        - yarn client:build

    - name: Copy Final Application Code for Distribution
      become: yes
      command: "{{item}}"
      with_items:
        - mkdir ~/app
        - cp -r ~/jarombek-com/dist/ ~/app/
        - rm -rf ~/jarombek-com