# Kubernetes deployments for the jarombek.com web application and database.
# Author: Andrew Jarombek
# Date: 11/10/2020

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarombek-com
  namespace: jarombek-com
  labels:
    version: v1.0.0
    environment: production
    application: jarombek-com
    task: web
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      version: v1.0.0
      application: jarombek-com
      environment: production
      task: web
  template:
    metadata:
      labels:
        version: v1.0.0
        environment: production
        application: jarombek-com
        task: web
    spec:
      containers:
        - name: jarombek-com
          image: ${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/jarombek-com:1.0.0
          readinessProbe:
            periodSeconds: 5
            initialDelaySeconds: 20
            httpGet:
              path: /
              port: 80
          ports:
            - containerPort: 80
              protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarombek-com-database
  namespace: jarombek-com
  labels:
    version: v1.0.0
    environment: production
    application: jarombek-com
    task: database
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      version: v1.0.0
      application: jarombek-com
      environment: production
      task: database
  template:
    metadata:
      labels:
        version: v1.0.0
        environment: production
        application: jarombek-com
        task: database
    spec:
      containers:
        - name: jarombek-com-database
          image: ${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/jarombek-com-database:1.0.0
          env:
            - name: NODE_ENV
              value: development
          ports:
            - containerPort: 27017
              protocol: TCP