# Kubernetes NodePort services for the jarombek.com web app and database.
# I hope you are doing okay.  Sending you ❤️.
# Author: Andrew Jarombek
# Date: 11/10/2020

apiVersion: v1
kind: Service
metadata:
  name: jarombek-com
  namespace: jarombek-com
  labels:
    version: v1.0.0
    environment: production
    application: jarombek-com
    task: web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    application: jarombek-com
    task: web

---

apiVersion: v1
kind: Service
metadata:
  name: jarombek-com-database
  namespace: jarombek-com
  labels:
    version: v1.0.0
    environment: production
    application: jarombek-com
    task: database
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    application: jarombek-com
    task: database