# Ansible Playbook for my web application's base AMI
# Author: Andrew Jarombek
# Date: 4/12/2019

- name: Base
  hosts: localhost
  connection: local
  become: yes
  vars:
    node_version: 8.11.3

  tasks:

    - name: Install Nginx
      shell: amazon-linux-extras install nginx1.12
      args:
        executable: /bin/bash

    - name: Enable Nginx
      shell: systemctl enable nginx
      args:
        executable: /bin/bash

    - name: Install nvm
      shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
      args:
        executable: /bin/bash

    - name: Install nvm
      shell: . ~/.nvm/nvm.sh
      args:
        executable: /bin/bash

    - name: Add nvm to .bash_profile
      shell: echo "export NVM_DIR=~/.nvm source" >> .bash_profile
      args:
        chdir: ~
        executable: /bin/bash

    - name: Add nvm to .bash_profile
      shell: echo "~/.nvm/nvm.sh" >> .bash_profile
      args:
        chdir: ~
        executable: /bin/bash

    - name: Debug
      shell: cat .bash_profile
      args:
        executable: /bin/bash

    - name: Install Node.js
      shell: nvm install {{ node_version }}
      args:
        executable: /bin/bash

    - name: Install Yarn Globally
      become: yes
      npm:
        name: yarn
        global: yes

    - name: Install PM2 Globally
      become: yes
      npm:
        name: pm2
        global: yes

    - name: Add CertBot Repository
      shell: curl -O http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      args:
        executable: /bin/bash

    - name: Upgrade All yum Packages
      yum:
        name: '*'
        state: latest

    - name: Install Certbot
      yum:
        name:
          - epel-release-latest-7.noarch.rpm
          - certbot
          - python2-certbot-nginx
        state: latest

    - name: Install Git
      yum:
        name: git
        state: latest